Repository urlshortenerteam/react_frontend, pull requests merged in 2020-08, with the labels that each got.

#67 theme_custom
  config-overrides.js
  cypress/integration/manage.spec.js
  cypress/integration/navi.spec.js
  cypress/integration/statistic.spec.js
  package.json
  src/components/adminManage/AdminUrlManagePageable.js
  src/components/adminManage/UserManage.js
  src/components/url-manage/SnapShot.js
  src/css/AdminStatisticsCss.css
  src/css/CreateCss.css
  src/css/LoginCss.css
  src/css/ManageCss.css
  src/css/NavigationCss.css
  src/css/Statistics.css
  src/css/theme.js
  src/css/theme.less
  src/index.js
  src/router/BasicRouter.js
Labels: enhancement

#68 fix : color
  src/components/Navigation.js
  src/components/adminManage/AdminUrlManagePageable.js
  src/components/create/ManyToOneTable.js
  src/components/create/OneToOneTable.js
  src/components/url-manage/UrlManagePanelPageable.js
  src/css/AdminStatisticsCss.css
  src/css/LoginCss.css
  src/css/ManageCss.css
  src/css/NavigationCss.css
  src/css/RegisterCss.css
  src/css/theme.less
  src/router/BasicRouter.js
  src/test/index.js
Labels: bug

#69 feat: selector for statistics
  package.json
  src/components/LineChart.js
  src/components/statistics/OverView.js
  src/components/statistics/TrendingLines.js
  src/css/HomeCss.css
  src/view/StatisticsView.js
Labels: enhancement

#70 feat : doc
  README.md
  src/components/MapBox.js
  src/components/Navigation.js
  src/css/AdminStatisticsCss.css
  src/services/viewContext.js
Labels: bug, enhancement

#71 feat: add microservice doc and toc
  README.md
Labels: documentation

#72 fix: peak value
  .babelrc
  README.md
  src/components/LineChart.js
  src/components/statistics/OverView.js
Labels: bug

#74 fix : disable create button
  README.md
  cypress/integration/create.spec.js
  src/components/adminManage/AdminUrlManagePageable.js
  src/components/create/ManyToOneTable.js
  src/components/create/OneToOneTable.js
  src/components/statistics/RealTimeTrack.js
  src/css/LoginCss.css
  src/view/LoginView.js
Labels: bug

#75 fix: none-working idle time counter
  README.md
  src/components/url-manage/UrlManagePanelPageable.js
  src/css/Statistics.css
  src/router/BasicRouter.js
  src/view/StatisticsView.js
Labels: bug, enhancement
