Repository urlshortenerteam/react_frontend, pull requests merged in 2020-07, with the labels that each got.

#59 Feature
  .elasticbeanstalk/config.yml
  .gitignore
  package.json
  src/components/MapBox.js
  src/css/Statistics.css
  src/css/StatisticsBarCss.css
  src/test/index.js
  src/view/StatisticsView.js
Labels: bug, enhancement

#60 Webpack
  .env.development
  .env.production
  cypress/integration/admin.spec.js
  package.json
  src/components/LineChart.js
  src/components/SearchBar.js
  src/components/adminManage/AdminUrlManage.js
  src/components/adminManage/UserManage.js
  src/components/adminManage/VisitRankingList.js
  src/components/create/ManyToOneTable.js
  src/components/create/OneToOneTable.js
  src/components/url-manage/UrlManagePanel.js
  src/css/HomeCss.css
  src/index.js
  src/router/BasicRouter.js
  src/router/PrivateRoute.js
  src/services/ajax.js
  src/services/urlService.js
  src/view/AdminManageView.js
  src/view/LoginView.js
  src/view/NoMatchView.js
  src/view/RegisterView.js
  src/view/StatisticsView.js
  test/public/static/alien.png
Labels: bug, enhancement

#61 fix: invisible text when searching in the map interface
  .env.development
  .env.production
  cypress/integration/statistic.spec.js
  public/bitbug_favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  serverless.yml
  src/components/MapBox.js
  src/components/statistics/RealTimeTrack.js
  src/css/Statistics.css
  src/services/ajax.js
  src/view/StatisticsView.js
Labels: bug

#54 update serverless deployment
  .github/workflows/deploy.yml
Labels: enhancement

#63 fix: optimization for bundle size
  cypress/integration/manage.spec.js
  package.json
  public/index.html
  src/css/LoginCss.css
  src/css/Statistics.css
  src/router/BasicRouter.js
  src/services/ajax.js
  src/view/StatisticsView.js
Labels: bug, enhancement

#64 Webpack
  .env.development
  .env.production
  cypress/integration/admin.spec.js
  cypress/integration/create.spec.js
  cypress/integration/manage.spec.js
  cypress/integration/navi.spec.js
  cypress/integration/statistic.spec.js
  src/components/Navigation.js
  src/components/adminManage/AdminUrlManage.js
  src/components/adminManage/DonutPlot.js
  src/components/adminManage/UserManage.js
  src/components/adminManage/VisitRankingList.js
  src/components/create/OneToOneTable.js
  src/components/url-manage/UrlManagePanel.js
  src/css/AdminStatisticsCss.css
  src/css/CreateCss.css
  src/css/HomeCss.css
  src/css/LoginCss.css
  src/css/ManageCss.css
  src/css/NavigationCss.css
  src/router/BasicRouter.js
  src/router/PrivateRoute.js
  src/services/ajax.js
  src/view/AdminManageView.js
  src/view/LoginView.js
  src/view/NoMatchView.js
Labels: bug, enhancement

#65 feat: loading page and quicker compiling by dynamic importing
  .babelrc
  .env.development
  .env.production
  config-overrides.js
  package.json
  public/flow.png
  public/logo200.png
  public/out2.webm
  public/people.png
  public/trans.png
  src/components/Loading.js
  src/components/Navigation.js
  src/components/adminManage/AdminUrlManage.js
  src/components/adminManage/NumberCount.js
  src/components/adminManage/VisitRankingList.js
  src/components/statistics/RealTimeTrack.js
  src/components/url-manage/UrlManagePanel.js
  src/css/AdminStatisticsCss.css
  src/router/PrivateRoute.js
  src/services/CreateService.js
  src/services/adminManageService.js
  src/services/ajax.js
  src/view/HomeView.js
  src/view/LoginView.js
  src/view/RegisterView.js
  src/view/StatisticsView.js
Labels: bug, enhancement

#66 Feature branch
  cypress/integration/admin.spec.js
  cypress/integration/manage.spec.js
  cypress/integration/statistic.spec.js
  src/components/Navigation.js
  src/components/adminManage/AdminStatistics.js
  src/components/adminManage/AdminUrlManagePageable.js
  src/components/adminManage/DonutPlot.js
  src/components/adminManage/NumberCount.js
  src/components/adminManage/UserManage.js
  src/components/adminManage/VisitRankingList.js
  src/components/create/ManyToOneTable.js
  src/components/create/OneToOneTable.js
  src/components/statistics/OverView.js
  src/components/url-manage/UrlManagePanelPageable.js
  src/css/AdminStatisticsCss.css
  src/css/CreateCss.css
  src/css/HomeCss.css
  src/css/LoginCss.css
  src/css/ManageCss.css
  src/css/NavigationCss.css
  src/css/NoMatchCss.css
  src/router/BasicRouter.js
  src/router/PrivateRoute.js
  src/services/adminManageService.js
  src/view/AdminManageView.js
  src/view/CreateView.js
  src/view/HomeView.js
  src/view/LoginView.js
  src/view/ManageView.js
  src/view/NoMatchView.js
  src/view/RegisterView.js
  src/view/StatisticsView.js
Labels: bug, enhancement
